services:
  - type: web
    name: django-lms
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString

databases:
  - name: lms-db
