services:
  - type: web
    name: ebmlms
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn ebm_lms.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ebmlms-db
          property: connectionString

databases:
  - name: ebmlms-db
